Add controllers
SergeyAseev/java-shareit pull request #1
Opened 2022-09-16 19:34 UTC by SergeyAseev

2022-09-17 20:56 UTC, alexache requested changes

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Boolean available;
По ТЗ должно быть еще одно поле - реквест

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Не должно быть использования стораджа из контроллера, тем более конкретной реализации

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        inMemoryUserStorage.getUserById(userId)
Контроллер не должен заниматься такой работой, это нарушает принцип Single Responsobility, сервис должен делать основную работу

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private User owner;
Пожалуй, это здесь лишнее поле,а вот реквест айди не хватает

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +   Item createItem(Item item, Long user);
Более логично получать на вход Dto объекты, и возвращает их же, а внутри использует маппер для конвертации и взаимодействия с репозиторием/стораджем

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    @GetMapping(value = "/{id}")
Не обязательно писать value=""

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    InMemoryItemStorage inMemoryItemStorage;
Не хватает модификаторов доступа у полей

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    UserService userService;
Можно обойтись использованием стораджа юзеров

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        users.remove(userId);
Можно обойтись только вызовом delete вместо get + delete. delete возвращает удаленный объект

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (inMemoryUserStorage.getAllEmails().contains(user.getEmail())) {
Сервис не должен быть настолько осведомленым о способе хранения в сторадже. При желании, можно сделать такой метод проверки уникальности в самом сторадже

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        getUserById(userId);
Можно бы оставить такую проверку в самом методе  удаления юзера стораджа

2022-09-17 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                .filter(item -> (item.getName().toLowerCase().contains(keyword.toLowerCase())
keyword.toLowerCase() лучше вынести в переменную, чтобы не происходила такая операция для каждого вызова фильтра

2022-09-19 20:30 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Исправлено

2022-09-19 20:30 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        inMemoryUserStorage.getUserById(userId)
Исправлено

2022-09-19 20:30 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +   Item createItem(Item item, Long user);
Исправлено

2022-09-19 20:30 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    @GetMapping(value = "/{id}")
Исправлено

2022-09-19 20:32 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    InMemoryItemStorage inMemoryItemStorage;
Исправлено

2022-09-19 20:33 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Boolean available;
Предполагал, что реквест нужно будет вводить в следующем ТЗ. Если ввести сейчас, то и класс придется создавать.

2022-09-19 20:36 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    UserService userService;
Не заметил замечания и наоборот убрал сторадж юзер...

2022-09-19 20:37 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                .filter(item -> (item.getName().toLowerCase().contains(keyword.toLowerCase())
Исправлено

2022-09-19 20:40 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        getUserById(userId);
Не очень понял. А зачем проверку переность в сторадж? Там кидать исключение вроде как нельзя, а значит придется возвращать что-то иное и обрабатывать исключение на уровне сервиса. Или я неправильно понял?

2022-09-19 20:44 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        users.remove(userId);
Не нашел такого метода ни у Set, ни у Map. В строке 48 идет удаление из списка email, где нужная почта вытягивается у пользователя по id, а после в 49 строке удаляется непосредственно сам пользователь.

2022-09-20 17:49 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private User owner;
owner убран. Реквест ID хочу добавить в следующем спринте.

2022-09-20 17:54 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (inMemoryUserStorage.getAllEmails().contains(user.getEmail())) {
Исправлено

2022-09-20 18:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Boolean available;
По ТЗ (а вернее по пояснениям ментора) класс реквеста тоже есть в данном спринте

2022-09-20 18:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        users.remove(userId);
```
User user = users.remove(userId);
emails.remove(user.getEmail());
```

2022-09-20 18:59 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        getUserById(userId);
Никто не запрещает кидать исключения из стораджа

2022-09-20 19:39 UTC, alexache approved these changes

2022-09-25 08:59 UTC, merged