Add bookings
SergeyAseev/java-shareit pull request #2
Opened 2022-09-29 17:19 UTC by SergeyAseev

2022-10-01 06:39 UTC, alexache requested changes

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/BookingStateEnum.java
> +public enum BookingStateEnum {
Лучше не использовать слово Enum в названии енама, как и Map в объекте мапы, и так далее

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatusEnum.java
> +public enum BookingStatusEnum {
Такой же комментарий про называние

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private UserService userService;
Почему бы тоже не сделать final и оставить на откуп @RequiredArgsConstructor?

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isApproved) {
Пожалуй лучше не смешивать валидацию и выставление статуса в этом методе, неочевидный эффект от вызова метода

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = UserMapper.toUser(userService.getUserById(userId));
Чтобы не делать конвертацию дважды - почему не использовать репозиторий юзеров вместа сервиса юзеров?

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemService.getItemByIdForBooking(bookingDto.getItemId());
Здесь видимо похожая проблема, только интерфейс еще и изменен для сервиса букинга. хотя можно работать с репозиторием без проблем

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> getALlByBooker(Long userId, String stateStr) {
Опечатка в назывании с лишней заглавной буквой в getAllByBooker?

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingStateEnum state;
Такой способ формирования списка бронирований в целом валидный, но далек от оптимального, базы данных и SQL запросы лучше подходят для обработки и фильтрации данных.
Если данных будет очень много, то придется в Java обрабатывать и фильтровать много данных, а это точно не лучшая сторона джава

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        User user = UserMapper.toUser(userService.getUserById(userId));
Тот же комментарий про двойное конвертирование

2022-10-01 06:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (commentDto.getText().isEmpty() || commentDto.getText().isBlank()) {
Логично иметь проверку в самом начале, чтобы делать меньше конвертаций/работы в противном случае

2022-10-01 08:20 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/model/BookingStateEnum.java
> +public enum BookingStateEnum {
Исправлено

2022-10-01 08:20 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatusEnum.java
> +public enum BookingStatusEnum {
Исправлено

2022-10-01 08:21 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> getALlByBooker(Long userId, String stateStr) {
исправлено

2022-10-01 08:24 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private UserService userService;
Исправлено

2022-10-01 08:30 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (isApproved) {
Исправлено

2022-10-01 08:32 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (commentDto.getText().isEmpty() || commentDto.getText().isBlank()) {
Исправлено

2022-10-02 08:50 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = UserMapper.toUser(userService.getUserById(userId));
Исправлено

2022-10-02 08:50 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemService.getItemByIdForBooking(bookingDto.getItemId());
Исправлено

2022-10-02 08:50 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        User user = UserMapper.toUser(userService.getUserById(userId));
Исправлено

2022-10-02 10:31 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingStateEnum state;
Уф. Попытки с третьей переделал. Кода в два раза больше пришлось написать(

2022-10-03 12:34 UTC, alexache approved these changes

2022-10-08 11:06 UTC, merged