Add item requests
SergeyAseev/java-shareit pull request #3
Opened 2022-10-12 20:46 UTC by SergeyAseev

2022-10-15 20:55 UTC, alexache requested changes

2022-10-15 20:55 UTC, alexache commented on pom.xml
> +												<minimum>0.6</minimum>
Это нельзя менять. нужно вернуть обратно

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    @Autowired
Это лишняя аннотация, так как уже есть @RequiredArgsContructor

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (item.getRequest() != null)
Почему это не написать бы в одной строкой с помощью тернатрного оператора?

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +/*        return Item.builder()
Закомментированного кода не должно быть

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +//@Builder
Закомментированного кода не должно быть

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public static class Item {
А почему не использовать ItemDto?

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    List<Item> items = itemRepository.findByRequest_Id(itemRequest.getId(), Sort.by("id").descending());
Можно сделать метод репозитория, который будет принимать на вход список request_id, и получать список items, чтобы не было слишком много отдельных вызовов

2022-10-15 20:55 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    List<Item> items = itemRepository.findByRequest_Id(itemRequest.getId(), Sort.by("id").descending());
Здесь такой же комментарий про список request_id

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    UserRepository userRepository;
Не хватает модификаторов доступа у полей

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserRepositoryTest.java
> +    UserRepository userRepository;
Модификаторы полей

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +class ItemRepositoryTest {
Не вижу еще BookingRepositoryTest, там тоже есть кастомный запрос

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        userService.createUser(UserMapper.toUserDto(user));
Такое лучше писать не в конструкторе, а в отдельных методах с соотсветствующими аннотациями @Before / @BeforeEach

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        userRepository.save(user);
Такой же комментарий про логику в конструкторе тест класса - лучше отдельные методы

2022-10-15 20:55 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +class BookingServiceTest {
Эти *ServiceTest какая-та смесь юнит-теста BookingService с интеграционными тестами. Должно быть и то, и другое в разных тест классах. Для юнит теста нужно мокать вызовы репозиториев.
Для интеграционных тестов можно реализовать меньше тест кейсов

2022-10-16 15:31 UTC, SergeyAseev commented on pom.xml
> +												<minimum>0.6</minimum>
Да, извиняюсь. Забыл вернуть. Покрытие было в районе 90%

2022-10-16 15:32 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    @Autowired
Исправлено

2022-10-16 15:40 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (item.getRequest() != null)
Готово

2022-10-16 15:44 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +/*        return Item.builder()
Готово

2022-10-16 15:44 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +//@Builder
Готово

2022-10-16 15:49 UTC, SergeyAseev commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    UserRepository userRepository;
Готово

2022-10-16 15:49 UTC, SergeyAseev commented on src/test/java/ru/practicum/shareit/user/UserRepositoryTest.java
> +    UserRepository userRepository;
Готово

2022-10-16 15:56 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public static class Item {
Потому, что невнимателен. Исправлено.

2022-10-17 19:45 UTC, SergeyAseev commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +class ItemRepositoryTest {
Готово

2022-10-17 20:38 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    List<Item> items = itemRepository.findByRequest_Id(itemRequest.getId(), Sort.by("id").descending());
Готово

2022-10-17 20:38 UTC, SergeyAseev commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    List<Item> items = itemRepository.findByRequest_Id(itemRequest.getId(), Sort.by("id").descending());
Готово

2022-10-17 21:15 UTC, SergeyAseev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +class BookingServiceTest {
Перенес часть тестов для bookingRepo в BookingRepositoryTest, но не уверен, что надо было делать именно так.

2022-10-18 18:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public static class ItemDto {
В целом я не столько про название, а про отдельный класс ItemDto, который уже есть. В чем отличие ItemRequestDto.ItemDto от ItemDto?

2022-10-18 18:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .map(e -> ItemRequestMapper.toItemRequestDto(e, items))
Мне кажется или здесь не проверяется какий item из items к какому itemRequest относится? То есть получается, что берутся все items и добавляются во все itemRequests

2022-10-18 18:44 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    User user1;
Пропущены модификаторы доступа

2022-10-18 18:44 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +class BookingServiceTest {
Возвращаясб к ТЗ;
1. "Реализовать юнит-тесты для всего кода, содержащего логику. Выберите те классы, которые содержат в себе нетривиальные методы, условия и ветвления. В основном это будут классы сервисов."
Юнит-тест сервиса означает, что репозиторий замокан. Такого теста нет (у всех сервисов)
2. "Реализовать интеграционные тесты, проверяющие взаимодействие с базой данных. Как вы помните, интеграционные тесты представляют собой более высокий уровень тестирования: их обычно требуется меньше, но покрытие каждого — больше. Мы предлагаем вам создать по одному интеграционному тесту для каждого крупного метода в ваших сервисах. Например, для метода getUserItems в классе ItemServiceImpl."
Твои текущие тесты сервисов напоминают нечто такое, но их можно меньшее количество.

2022-10-18 18:45 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +class BookingServiceTest {
То есть получается. что ты сделал сложнее, чем требовалось, и такие тесты будет сложно поддерживать

2022-10-18 18:46 UTC, alexache approved these changes

2022-10-19 21:04 UTC, merged